using System.Diagnostics;
using Microsoft.CodeAnalysis;

namespace EFCore.Sourcegen
{
    [Generator]
    public class HelloSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
    //         while (!System.Diagnostics.Debugger.IsAttached)
    // System.Threading.Thread.Sleep(500);

    //         Debugger.Break();
            // Find the main method
            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

            // Build up the source code
            string source = $@"// <auto-generated/>
using Microsoft.EntityFrameworkCore.Design;

[assembly: DesignTimeServicesReference(
""EFCore.Sqlite.Concurrency.EFCoreSqliteConcurrencyDesignTimeServices, EFCore.Sqlite.Concurrency"",
""Microsoft.EntityFrameworkCore.Sqlite"")]
";
            var typeName = mainMethod.ContainingType.Name;

            // Add the source code to the compilation
            context.AddSource($"{typeName}.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization required for this one
        }
    }
}